pipeline:
  name: nags-pipeline
  identifier: nagspipeline
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: IAC
        identifier: IAC
        description: ""
        type: IACM
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          workspace: nagasaiworkspace
          execution:
            steps:
              - step:
                  type: IACMTerraformPlugin
                  name: init
                  identifier: init
                  timeout: 10m
                  spec:
                    command: init
              - step:
                  type: IACMTerraformPlugin
                  name: plan
                  identifier: plan
                  timeout: 10m
                  spec:
                    command: plan
              - parallel:
                  - step:
                      type: IACMTerraformPlugin
                      name: apply
                      identifier: apply
                      timeout: 10m
                      spec:
                        command: apply
                  - step:
                      type: IACMTerraformPlugin
                      name: IACMTerraformPlugin_4
                      identifier: IACMTerraformPlugin_4
                      spec:
                        command: destroy
                      timeout: 1h
        tags: {}
  variables:
    - name: terraform
      type: String
      description: ""
      required: true
      value: apply
    - name: tfdestroy
      type: String
      description: ""
      required: true
      value: destroy
